### ISSUE TITLE
/var/vcap/store/elasticsearch Filling up Quickly

### ISSUE THREAD

**Issue by kumarganesh2814** [pivotal-cf/docs-metrics#98]
Hi Team,

We have got issue and a critical /var/vcap/store/elasticsearch directory in elastic search Master VM we see its filling quickly

```
elasticsearch_data/db7ea5f9-2f8e-4dc9-aa90-71ffb3f8c459:/var/vcap/store/elasticsearch$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc1       296G  237G   44G  85% /var/vcap/store
elasticsearch_data/db7ea5f9-2f8e-4dc9-aa90-71ffb3f8c459:/var/vcap/store/elasticsearch$
```

When I checked logs I see 

```
elasticsearch_data/db7ea5f9-2f8e-4dc9-aa90-71ffb3f8c459:~$ tail -300f /var/vcap/sys/log/elasticsearch/elasticsearch.stdout.log
[2018-07-10 02:03:45,502][WARN ][bootstrap                ] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: /tmp/jna-3613596/jna8452816065285115642.tmp: /tmp/jna-3613596/jna8452816065285115642.tmp: failed to map segment from shared object: Operation not permitted
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:761)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736)
        at com.sun.jna.Native.<clinit>(Native.java:131)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45)
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:89)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:144)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
[2018-07-10 02:03:45,504][WARN ][bootstrap                ] cannot check if running as root because JNA is not available
[2018-07-10 02:03:45,504][WARN ][bootstrap                ] cannot install syscall filters because JNA is not available
[2018-07-10 02:03:45,504][WARN ][bootstrap                ] cannot mlockall because JNA is not available
```

Also from cf app of metrics-v1-4 I see errors as

```
bosh-prod:~ → cf logs mysql-logqueue --recent
Connected, dumping recent logs for app mysql-logqueue in org system / space metrics-v1-4 as ganeshk@vmware.com...

2018-07-11T00:22:22.95-0700 [API/0]      OUT Updated app with guid 351262c7-d349-421f-b946-2e6200a3a3b8 ({"state"=>"STOPPED"})
2018-07-11T00:22:23.63-0700 [API/1]      OUT Updated app with guid 351262c7-d349-421f-b946-2e6200a3a3b8 ({"state"=>"STARTED"})
2018-07-11T01:04:58.25-0700 [APP/PROC/WEB/0]OUT 2018-07-11T01:04:58.253881Z 14 GetEnv ERROR: Unable to remove job: app_metric_593d65c6_5e01_4552_bffc_363a5c2eb88e_1531267200 from metrics-jobs
2018-07-11T01:04:58.25-0700 [APP/PROC/WEB/0]OUT 2018-07-11T01:04:58.259736Z 14 GetEnv ERROR: Unable to remove job: app_metric_6e4aca24_e104_4678_b5b5_2e4c0a3df704_1531267200 from metrics-jobs
2018-07-11T01:04:58.26-0700 [APP/PROC/WEB/0]OUT 2018-07-11T01:04:58.265595Z 14 GetEnv ERROR: Unable to remove job: app_metric_7968b2ae_ba00_429d_9f7b_e9bd9fb68942_1531267200 from metrics-jobs
````

Can you Please advise how to resolve this quickly

Best Regards
Ganesh

**Comment by mrinehart13** [comment]
Hi @kumarganesh2814,

This repo is for requesting changes to the PCF Metrics online documentation. For your issue, I would suggest contacting Pivotal Support to make sure your report is routed and handled correctly.

Without knowing more about your environment, the suggested mitigation for ElasticSearch reaching capacity is to scale by adding more logs data storage nodes.

Please contact Support for more details.

Thank you,
Matt
